# Generated by Django 5.2.6 on 2025-09-18 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_alter_rol_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(help_text="Descripción legible de la acción (ej: 'médico Pedro eliminó al paciente Juanito')")),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('objeto', models.CharField(blank=True, help_text="Texto corto indicando el objeto afectado (ej: 'Paciente: Juanito (id:4)')", max_length=200, null=True)),
                ('extra', models.JSONField(blank=True, help_text='Información adicional en JSON (opcional)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='Gestion.usuario')),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-timestamp'],
            },
        ),
    ]
